version: '3.8'

services:
  backend:
    image: al3eon/yandex-reviews-service:latest
    container_name: review_app_prod
    restart: always
    command: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./static:/app/app/static

  parser:
    image: al3eon/yandex-reviews-service:latest
    container_name: review_parser_prod
    restart: always
    command: >
      sh -c "while true; do 
               echo 'Starting parser...';
               python -m scraper.run_parser; 
               echo 'Done. Sleeping 6 hours...';
               sleep  72000; 
             done"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./static:/app/app/static
    depends_on:
      chrome:
        condition: service_healthy

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: review_chrome
    restart: always
    shm_size: '2gb'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: review_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend